device: cuda
workdir: 'workdirs'
n_way: 5
k_shot: 1
n_query: 1
n_seg: 4
eval_interval: 1
ckpt_interval: 2000
dataset:
  train:
    num_episodes: 2
    root_dir: 'ucf101_sample'
    class_path: 'ucf101_sample/train.json'
  val:
    num_episodes: 1
    root_dir: 'ucf101_sample'
    class_path: 'ucf101_sample/val.json'
  test:
    num_episodes: 1
    root_dir: 'ucf101_sample'
    class_path: 'ucf101_sample/test.json'

pretrained:

log: False
wandb:
  project: 'few-shot-action-recognition'
  group: 'ucf101_c3d'
  secret_file: 'secret_key.yaml'

